/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Tag = IDL.Variant({
  'y2k' : IDL.Null,
  'techwear' : IDL.Null,
  'futuristic' : IDL.Null,
  'streetwear' : IDL.Null,
  'old_school' : IDL.Null,
});
export const Category = IDL.Variant({
  'accessories' : IDL.Null,
  'tops' : IDL.Null,
  'bottoms' : IDL.Null,
  'outerwear' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'tag' : Tag,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addEmail' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'getAllEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProductsByTag' : IDL.Func([Tag], [IDL.Vec(Product)], ['query']),
  'seedProducts' : IDL.Func([], [], []),
  'updateProduct' : IDL.Func([ProductId, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Tag = IDL.Variant({
    'y2k' : IDL.Null,
    'techwear' : IDL.Null,
    'futuristic' : IDL.Null,
    'streetwear' : IDL.Null,
    'old_school' : IDL.Null,
  });
  const Category = IDL.Variant({
    'accessories' : IDL.Null,
    'tops' : IDL.Null,
    'bottoms' : IDL.Null,
    'outerwear' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'tag' : Tag,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addEmail' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'getAllEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByTag' : IDL.Func([Tag], [IDL.Vec(Product)], ['query']),
    'seedProducts' : IDL.Func([], [], []),
    'updateProduct' : IDL.Func([ProductId, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };