/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'accessories' : null } |
  { 'tops' : null } |
  { 'bottoms' : null } |
  { 'outerwear' : null };
export interface Product {
  'id' : ProductId,
  'tag' : Tag,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
}
export type ProductId = bigint;
export type Tag = { 'y2k' : null } |
  { 'techwear' : null } |
  { 'futuristic' : null } |
  { 'streetwear' : null } |
  { 'old_school' : null };
export interface _SERVICE {
  'addEmail' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], ProductId>,
  'getAllEmails' : ActorMethod<[], Array<string>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getProductsByTag' : ActorMethod<[Tag], Array<Product>>,
  'seedProducts' : ActorMethod<[], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];